# Generated by Django 3.1.3 on 2023-09-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_auto_20230706_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='Course',
            field=models.ManyToManyField(to='onlinecourse.Course'),
        ),
    ]
